os: linux
dist: bionic
language: java

jdk: openjdk11

jobs:
  include:
    - stage: Maven
      before_script:
        - cd backend-server
      script:
        - mvn clean install -DskipTests

notifications:
  email: false 